server:
  servlet:
    context-path: /shiro001
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/shiro?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    maxActive: 20
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: ["classpath:/static/"]
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  jpa:
    show-sql: true
mybatis:
  type-aliases-package: com.hwua.po
  mapper-locations: classpath:mappers/*.xml
logging:
  level: {"com.hwua": "trace"}




